name: ItemBuilder
version: '${project.version}'
main: dev.ruster.itembuilder.ItemBuilder
api-version: 1.18
depend: [ ProtocolLib ]
authors: [ Ruster ]
description: A simple API to create ItemStack easier
